version: "3"
services:
  postgres:
    image: postgres:14.11-alpine3.19
    container_name: postgres_14
    environment:
      POSTGRES_DB: muatmuat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: